---
name: dependabot-auto-merge

on:
  pull_request:

permissions: {}

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' && github.repository == 'andreygrechin/gitree' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@08eff52bf64351f401fb50d4972fa95b9f2c2d1b # v2.4.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve Dependabot PR
        if: contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.dependabot-metadata.outputs.update-type) && steps.dependabot-metadata.outputs.dependency-type == 'all'
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Enable auto-merge
        if: contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.dependabot-metadata.outputs.update-type) && steps.dependabot-metadata.outputs.dependency-type == 'all'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
